Staking: Init pool, add stake
jet-lab/jet-engine pull request #24
Opened 2022-01-11 17:15 UTC by Tristyn

New style for the lib. Really happy how it's turning out. Especially stakeAccount.ts

2022-01-11 18:33 UTC, callensm requested changes

2022-01-11 18:33 UTC, callensm commented on package.json
> +  "version": "0.2.3",
```suggestion
  "version": "0.2.2",
```
This should be changed by `npm version patch` which also pushes a new tag to the repository once PR has landed on `master`.

2022-01-11 19:09 UTC, qiqicodes commented on src/common/index.ts
> +import { DerivedAccount } from ".."
DerivedAccount doesn't exist currently.

2022-01-11 19:46 UTC, qiqicodes approved these changes
LGTM =]

2022-01-12 10:24 UTC, Tristyn commented
This was my first rebase :)

2022-01-12 11:06 UTC, Tristyn commented
For some reason I accepted Matts change but it's the change is still not accepted

2022-01-12 13:02 UTC, callensm approved these changes

2022-01-12 13:02 UTC, merged