Add token amount
jet-lab/jet-engine pull request #30
Opened 2022-01-25 08:54 UTC by GHesericsu

converted availableLiquidity from BN to TokenAmount

2022-01-25 14:33 UTC, Tristyn requested changes
This is great dude! Awesome bug fixes

Looks like you're deserializing the mint then calling a function that deserializes it again.
Remember the DRY principle. Don't Repeat Yourself

2022-01-25 14:33 UTC, Tristyn commented on src/pools/reserve.ts
> +      new TokenAmount(new BN(availableLiquidity), parseMintAccount(mintInfo.data).decimals, data.tokenMint)
You are parsing the mint twice, once in this method and once in decodeReserveData (Same decoding the mint twice in loadMultiple()). I recommend you do each step once..
```suggestion
      new BN(availableLiquidity)
```

2022-01-25 14:33 UTC, Tristyn commented on src/pools/reserve.ts
> +        )
```suggestion
        vaults[i].amount
```

2022-01-25 14:33 UTC, Tristyn commented on src/pools/reserve.ts
> +      new TokenAmount(new BN(availableLiquidity), parseMintAccount(mintInfo.data).decimals, this.data.tokenMint)
```suggestion
      new BN(availableLiquidity)
```

2022-01-25 14:33 UTC, Tristyn commented on src/pools/reserve.ts
> +    availableLiquidity: TokenAmount
```suggestion
    availableLiquidity: BN
```

2022-01-25 14:33 UTC, Tristyn commented on src/pools/reserve.ts
>      const mint = parseMintAccount(mintData)
.

2022-01-25 14:33 UTC, Tristyn commented on src/pools/reserve.ts
>      const mint = parseMintAccount(mintData)
```suggestion
    availableLiquidityLamports: BN
  ) {
    const mint = parseMintAccount(mintData)
    const availableLiquidity = new TokenAmount(availableLiquidity, mint.decimals, data.tokenMint)
    const state = ReserveStateStruct.decode(new Uint8Array(data.state))
```

2022-01-25 19:38 UTC, callensm approved these changes

2022-01-26 16:28 UTC, Tristyn approved these changes

2022-01-26 16:28 UTC, merged