Change bn to u64 to match back-end
jet-lab/jet-engine pull request #51
Opened 2022-02-25 17:29 UTC by rhubarbgarden

Also added calculation for amount of votes per share in governance

2022-02-25 17:37 UTC, callensm commented
Is this meant to just be a semantic change? `BN` and `u64` are functionally the same.

2022-02-25 18:11 UTC, Tristyn requested changes
The useBalance change is cool

I would not use u64 over BN because of a couple issues

2022-02-25 18:11 UTC, Tristyn commented on src/staking/stakeAccount.ts
> +      jetVotesPerShare = stakePool.vault.amount.div(stakePool.stakePool.sharesBonded)
`stakedJet` looks right, but I think this one would have a division rounding issue, do you need to multiply it by another BN first then divide last to get the votes balance?

2022-02-25 18:20 UTC, Tristyn commented
> Is this meant to just be a semantic change? `BN` and `u64` are functionally the same.
> 
> Only adds two `Buffer` related functions to the class definitions:
> 
> ```ts
>  export class u64 extends BN {
>     toBuffer(): Buffer;
>     static fromBuffer(buffer: Buffer): u64;
>   }
> ```

It ensures buffers are 8 bytes, but anchor is smart enough to handle any sized buffers. u64 came from spl-token before anchor was a thing

2022-02-26 08:20 UTC, rhubarbgarden commented on src/staking/stakeAccount.ts
> +      jetVotesPerShare = stakePool.vault.amount.div(stakePool.stakePool.sharesBonded)
`jetVotesPerShare` will be a different calculation than `stakedJet` - the program will panic if trying to mint less than one share's worth of votes (even if that is what the user is owed) so jetVotesPerShare calculates what that number of votes will be

2022-02-26 08:25 UTC, rhubarbgarden commented on src/staking/stakeAccount.ts
> +    let stakedJet: u64 = new u64(0)
Will change this to allow for undefined values before accounts have loaded

2022-02-26 16:07 UTC, Tristyn approved these changes
Looks good to merge, you might run into trouble using the jetPerStakedShare because it gets rounded to a whole number

2022-02-26 16:11 UTC, Tristyn commented on src/staking/stakeAccount.ts
> +      jetVotesPerShare = stakePool.vault.amount.div(stakePool.stakePool.sharesBonded)
Maybe we should skip minting votes if there's not enough room to mint

2022-02-26 16:22 UTC, rhubarbgarden commented on src/staking/stakeAccount.ts
> +      jetVotesPerShare = stakePool.vault.amount.div(stakePool.stakePool.sharesBonded)
The way I have it implemented rn is that if the value of the remaining votes is less than one share, we don't mint anything at all. Is that similar to what you were thinking?

2022-02-27 05:54 UTC, rhubarbgarden commented on src/staking/stakePool.ts
> +    const jetVotesPerShare = vault.amount.div(stakePool.sharesBonded)
I'm not entirely sure I understand, could you elaborate?

2022-02-27 11:30 UTC, merged